# Generated by Django 5.2 on 2025-11-25 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_url', models.URLField(blank=True, help_text='Landing page / form URL', null=True)),
                ('from_domain', models.CharField(blank=True, max_length=200)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=200)),
                ('utm_term', models.CharField(blank=True, max_length=200)),
                ('gclid', models.CharField(blank=True, max_length=255)),
                ('is_ads', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='The TeamMember responsible for this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='Travel.teammember')),
            ],
        ),
    ]
