# Generated by Django 5.2 on 2025-12-10 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0002_lead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayitinerary',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'Day Itinerary', 'verbose_name_plural': 'Day Itineraries'},
        ),
        migrations.AddField(
            model_name='dayitinerary',
            name='image_source',
            field=models.CharField(choices=[('gallery', 'From Gallery'), ('upload', 'Upload New')], default='upload', help_text='Choose image from gallery or upload new', max_length=10),
        ),
        migrations.AddField(
            model_name='dayitinerary',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pin this itinerary to show first'),
        ),
        migrations.AddField(
            model_name='dayitinerary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dayitinerary',
            name='uploaded_image',
            field=models.ImageField(blank=True, help_text='Upload new image directly', null=True, upload_to='day_itinerary_images/'),
        ),
        migrations.AlterField(
            model_name='dayitinerary',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Travel.teammember'),
        ),
        migrations.AlterField(
            model_name='dayitinerary',
            name='destination',
            field=models.CharField(help_text="Enter destination name (e.g., 'Munnar', 'Cochin')", max_length=255),
        ),
        migrations.AlterField(
            model_name='dayitinerary',
            name='details',
            field=models.TextField(help_text='Full day itinerary description'),
        ),
        migrations.AlterField(
            model_name='dayitinerary',
            name='name',
            field=models.CharField(help_text="e.g., 'Cochin to Munnar (135 Km, 3.00 Hrs)'", max_length=255),
        ),
        migrations.CreateModel(
            name='ItineraryImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Image name (e.g., 'Sunset Beach', 'Mountain View')", max_length=255)),
                ('image', models.ImageField(help_text='Upload reusable itinerary image', upload_to='itinerary_gallery/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Travel.teammember')),
            ],
            options={
                'verbose_name': 'Itinerary Gallery Image',
                'verbose_name_plural': 'Itinerary Gallery Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dayitinerary',
            name='gallery_image',
            field=models.ForeignKey(blank=True, help_text='Select from existing gallery images', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='day_itineraries', to='Travel.itineraryimagegallery'),
        ),
    ]
