# Generated by Django 5.2 on 2025-12-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Travel",
            "0003_alter_dayitinerary_options_dayitinerary_image_source_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="query_id",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="query",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("active", "Active"),
                    ("no_connect", "No Connect"),
                    ("follow_up", "Follow Up"),
                    ("proposal_sent", "Proposal Sent"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("invalid", "Invalid"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
