# Generated by Django 5.2 on 2025-12-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Travel", "0004_query_query_id_query_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="query",
            name="query_id",
            field=models.CharField(
                blank=True, db_index=True, editable=False, max_length=20, unique=True
            ),
        ),
    ]
