# Generated by Django 5.2 on 2025-12-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Travel", "0005_alter_query_query_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclebooking",
            name="option",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="vehiclebooking",
            name="pickup_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehiclebooking",
            name="vehicle_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
