# Generated by Django 5.2 on 2025-12-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Travel", "0006_alter_vehiclebooking_option_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="houseboatbooking",
            name="option",
            field=models.CharField(
                choices=[
                    ("option1", "Option 1"),
                    ("option2", "Option 2"),
                    ("option3", "Option 3"),
                ],
                default="option1",
                help_text="Pricing option for this houseboat",
                max_length=10,
            ),
        ),
    ]
