# Generated by Django 5.2 on 2025-12-31 09:20

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Travel", "0007_houseboatbooking_option"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItineraryPackageTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "special_inclusion",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Special Inclusion"
                    ),
                ),
                (
                    "package_inclusion",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Package Inclusion"
                    ),
                ),
                (
                    "package_exclusion",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Package Exclusion"
                    ),
                ),
                (
                    "terms_and_conditions",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Terms and Conditions"
                    ),
                ),
                (
                    "payment_policy",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Payment Policy"
                    ),
                ),
                (
                    "cancellation_policy",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Cancellation Policy"
                    ),
                ),
                (
                    "refund_policy",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Refund After Cancellation"
                    ),
                ),
                (
                    "list_of_documents",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="List of Documents Required"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "itinerary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_package_terms",
                        to="Travel.itinerary",
                        verbose_name="Itinerary",
                    ),
                ),
            ],
            options={
                "verbose_name": "Itinerary Package Terms",
                "verbose_name_plural": "Itinerary Package Terms",
                "ordering": ["-created_at"],
            },
        ),
    ]
