# Generated by Django 5.2 on 2026-01-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Travel", "0008_itinerarypackageterms"),
    ]

    operations = [
        migrations.AddField(
            model_name="itinerary",
            name="version_number",
            field=models.IntegerField(
                default=1,
                help_text="Version number of this itinerary (1, 2, 3...)",
                verbose_name="Version Number",
            ),
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="archived_reason",
            field=models.CharField(
                blank=True,
                help_text="Why was this itinerary archived",
                max_length=255,
                null=True,
                verbose_name="Archive Reason",
            ),
        ),
        migrations.AlterField(
            model_name="itinerary",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Itinerary Name"),
        ),
        migrations.AddIndex(
            model_name="itinerary",
            index=models.Index(
                fields=["version_number"], name="Travel_itin_version_8f23de_idx"
            ),
        ),
    ]
