# Generated by Django 5.2 on 2026-01-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Travel", "0009_itinerary_version_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelbooking",
            name="custom_hotel_name",
            field=models.CharField(
                blank=True,
                help_text="For Demo Hotels not in the database",
                max_length=255,
                null=True,
            ),
        ),
    ]
