# Generated by Django 5.2 on 2026-01-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Travel", "0010_hotelbooking_custom_hotel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destinations",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
