# Generated by Django 5.2 on 2026-01-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Travel", "0011_alter_destinations_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelbooking",
            name="custom_room_type",
            field=models.CharField(
                blank=True,
                help_text="For manually typed room types",
                max_length=100,
                null=True,
            ),
        ),
    ]
