# Generated by Django 5.2 on 2026-01-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Travel", "0012_hotelbooking_custom_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelbooking",
            name="option",
            field=models.CharField(
                choices=[
                    ("option_1", "Standard"),
                    ("option_2", "Deluxe"),
                    ("option_3", "Premium"),
                ],
                max_length=10,
            ),
        ),
    ]
