# Generated by Django 5.2 on 2026-01-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Travel", "0013_alter_hotelbooking_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelbooking",
            name="option",
            field=models.CharField(
                choices=[
                    ("option_1", "Standard"),
                    ("option_2", "Deluxe"),
                    ("option_3", "Premium"),
                    ("option_4", "Luxury"),
                ],
                max_length=10,
            ),
        ),
    ]
