# Generated by Django 5.2 on 2026-01-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Travel", "0014_alter_hotelbooking_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="houseboatbooking",
            name="option",
            field=models.CharField(
                choices=[
                    ("option1", "Standard"),
                    ("option2", "Deluxe"),
                    ("option3", "Premium"),
                    ("option4", "Luxury"),
                ],
                default="option1",
                help_text="Pricing option for this houseboat",
                max_length=10,
            ),
        ),
    ]
