# Generated by Django 5.2 on 2026-01-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Travel", "0015_alter_houseboatbooking_option"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="hotelprice",
            constraint=models.UniqueConstraint(
                fields=("hotel", "room_type", "meal_plan", "from_date", "to_date"),
                name="unique_hotel_room_meal_date_range",
            ),
        ),
    ]
