# Generated by Django 5.2 on 2026-02-05 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Travel", "0016_hotelprice_unique_hotel_room_meal_date_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityprice",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="Travel.activity",
            ),
        ),
    ]
