# Generated by Django 5.2 on 2026-02-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Travel", "0017_alter_activityprice_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="query",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
