# Generated by Django 5.2 on 2026-02-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0018_alter_query_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
